name: Dummy Docker Custom Action
description: Dummy Docker Custom Action
inputs:
  sample_input:
    required: false
    description: sample input to send to js
    default: This comes from dummy js action
outputs:
  sample_output:
    description: Sample input to send from js
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.sample_input }}
  
