name: Demo Cache use
on: workflow_dispatch
jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-dependency-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
