name: Use Custom Action
on: workflow_dispatch
jobs:
  use_custom_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3
      - name: Using custom action
        uses: ./.github/actions/dummy-composite
        with:
          custom_message: "This comes from dummy use custom action"
