name: Use Custom Action
on: workflow_dispatch
jobs:
  use_custom_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3
      - name: Using custom action
        id: dummy-composite
        uses: ./.github/actions/dummy-composite
        with:
          custom_message: "This comes from dummy use custom action"
      - name: Print output from custom action
        run: echo "${{ steps.dummy-composite.outputs.custom_output }}"
