name: Dummy permissions job
on: [issues]
jobs:
  secure_job:
    runs-on: ubuntu-latest
    permissions: 
      issues: write
    steps:
      - name: Write on issue
        run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: triage
