name: Dummy matrix strategy
on: [workflow_dispatch]
jobs:
  matrix:
    strategy:
      matrix:
        echo1: ['HI', 'HELLO']
        echo2: ['Joe', 'John']
    runs-on: ubuntu-latest
    steps:
      - name: Print Variables
        run: echo "${{ matrix.echo1 }}" "${{ matrix.echo2 }}"
      
        
