name: Dummy permissions job
on: [issues]
jobs:
  secure_job:
    runs-on: ubuntu-latest
    permissions: 
      issues: write
    steps:
      - name: Write on issue
        run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: triage
  
  # Example to show how to use OpenID. To make it work we would require a docker/js action to deploy the website.
  iam-aws:
    if: false
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Get AWS Permissions
        uses: aws-actions/configure-aws-credentials
        with:
          role-to-assume: arn:aws:iam::450226343468:role/GitHubDemo1
          aws-region: us-east-1
      - name: Deploy site
        uses: ./.github/actions/deploy-s3-docker
        with:
          bucket: bucket-name
          dist-folder: dist
