name: Demo Artifact
on: workflow_dispatch
jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        run: echo "Test" > test.txt
      - name: Generate Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact-demo
          path: test.txt
  use-artifact:
    needs: artifact
    runs-on: ubuntu-latest
    steps:
      - name: Get Artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact-demo
      - name: Print artifact content
        run: cat test.txt
